version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    ports:
      - 9292:9292
      - 8787:8787
    restart: unless-stopped
    volumes:
      - ./target/oidc-mapper-1.0-SNAPSHOT.jar:/opt/keycloak/providers/oidc-mapper-1.0-SNAPSHOT.jar
    entrypoint:
      - /opt/keycloak/bin/kc.sh
      - start-dev
      - --http-relative-path
      - /auth
      - --http-port
      - "9292"
      - --hostname-strict
      - "false"
      - --features=token-exchange
      - --spi-connections-http-client-default-socket-timeout-millis=10000
      - --debug
      - --db
      - postgres
      - --log-level
      - INFO,org.example:DEBUG
    environment:
      - KC_DB_PASSWORD=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL=jdbc:postgresql://postres.host:5432/keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Pa55w0rd
      - DEBUG_PORT='*:8787'
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M
